spring.application.name=truth-keeper
server.port=9001
spring.datasource.username=keeper_of_truths
spring.datasource.password=coolpw
spring.datasource.url=jdbc:postgresql://localhost:5432/truthdb
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

truth-sayer.cors.origins=http://localhost:4200

swish.key=src/main/resources/test-certificates/Swish_Merchant_TestCertificate_1234679304.key
swish.cert=src/main/resources/test-certificates/Swish_Merchant_TestCertificate_1234679304.pem
swish.cacert=src/main/resources/test-certificates/Swish_TLS_RootCA.pem
swish.callBackUrl=https://ourcoolcallback.se
swish.amount=10
swish.currency=SEK
swish.message=En till sanning till folket!
swish.payeeAlias=telefonnummer!